---
- name: vorta role
  tags:
  - vorta
  block:

  # assert
  - name: Check vars for vorta role
    ansible.builtin.assert:
      that:
      - vorta_user != None
      - vorta_repo_host != None
      - vorta_repo_path != None
      - vorta_repo_ssh_private_key_file != None
      - vorta_repo_pw != None

  # make sure user exists
  - name: Check if user exists {{ vorta_user }}
    command: "getent passwd {{ vorta_user }}"
    changed_when: false
      
  - ansible.builtin.import_tasks: vorta-apt.yml
  - ansible.builtin.import_tasks: vorta-flatpak.yml
  - ansible.builtin.import_tasks: vorta-config.yml
  - ansible.builtin.import_tasks: vorta-autostart.yml
  - ansible.builtin.import_tasks: vorta-ssh.yml

  # systemd_unit
  - name: Configure systemd units
    ansible.builtin.include_tasks: vorta-systemd-unit.yml
    loop: "{{ vorta_systemd_units }}"
    loop_control:
      loop_var: item
      label: "{{ item.name }}"