---
- tags: [vorta-ssh]
  when: vorta_repo_ssh_private_key_file != None
  block:

  # mkdir
  - name: Mkdir /home/{{ vorta_user }}/.ssh
    become: true
    ansible.builtin.file:
      path: "/home/{{ vorta_user }}/.ssh"
      state: directory
      mode: u=rwx,g=,o=
      owner: "{{ vorta_user }}"
      group: "{{ vorta_user }}"

  # cp priv key
  - name: Copy private ssh key
    become: true
    ansible.builtin.copy:
      src: "{{ vorta_repo_ssh_private_key_file }}"
      dest: "/home/{{ vorta_user }}/.ssh/{{ vorta_repo_ssh_private_key_file }}"
      owner: "{{ vorta_user }}"
      group: "{{ vorta_user }}"
      mode: u=rw,g=,o=